"""Render the pipeline results into downloadable files.

Human-readable (Markdown, HTML) and machine-readable (JSON, CSV) outputs are
all rendered from the same verified ``MeetingRecord`` object, so they always
contain exactly the same decisions and tasks.
"""
from __future__ import annotations

import csv
import html
import io
import json
import zipfile
from pathlib import Path

from .refine import _ts
from .schema import Correction, MeetingRecord, Transcript, UNSPECIFIED


def transcript_txt(t: Transcript, title: str) -> str:
    lines = [f"# {title}", f"# model: {t.model}", ""]
    lines += [f"[{_ts(s.start)} - {_ts(s.end)}] {s.text}" for s in t.segments]
    return "\n".join(lines) + "\n"


def transcript_json(t: Transcript) -> list[dict]:
    return [{"id": s.id, "start": s.start, "end": s.end, "text": s.text} for s in t.segments]


def _when(start) -> str:
    return _ts(start) if start is not None else "—"


def record_markdown(rec: MeetingRecord) -> str:
    md = [f"# {rec.title}", ""]
    meta = rec.metadata
    facts = []
    if meta.get("source_file"):
        facts.append(f"**Recording:** {meta['source_file']}")
    if meta.get("duration_s"):
        facts.append(f"**Duration:** {_ts(meta['duration_s'])}")
    if rec.participants:
        facts.append(f"**People mentioned:** {', '.join(rec.participants)}")
    if facts:
        md += [" · ".join(facts), ""]
    md += ["## Summary", "", rec.summary or "_No summary produced._", ""]

    md += ["## Minutes", ""]
    if rec.minutes:
        for sec in rec.minutes:
            md.append(f"### {sec.topic}")
            md += [f"- {p}" for p in sec.points] + [""]
    else:
        md += ["_No minutes produced._", ""]

    md += ["## Key decisions", ""]
    if rec.decisions:
        for d in rec.decisions:
            md.append(f"{d.id}. **{d.decision}**  ")
            md.append(f"   _[{_when(d.evidence.start)}] “{d.evidence.quote}”_")
        md.append("")
    else:
        md += ["_No decisions were explicitly agreed in this recording._", ""]

    md += ["## Action items", ""]
    if rec.action_items:
        md += ["| # | Task | Owner | Deadline | Said at |", "|---|---|---|---|---|"]
        for t in rec.action_items:
            md.append(f"| {t.id} | {_md_cell(t.task)} | {_md_cell(t.owner)} | {_md_cell(t.deadline)} | "
                      f"{_when(t.evidence.start)} |")
        md.append("")
        md.append("_Owner/deadline “Unspecified” means the recording did not state one._")
        md.append("")
    else:
        md += ["_No action items were identified._", ""]

    if rec.open_items:
        md += ["## Open items (not agreed)", ""]
        for o in rec.open_items:
            md.append(f"- **{o.kind.capitalize()}:** {o.item}")
        md.append("")

    md += ["## Verification", ""] + [f"- {line}" for line in rec.verification_log] + [""]
    models = meta.get("models", {})
    if models:
        md += ["---", "",
               f"_Generated by MeetScribe · speech-to-text: {models.get('stt')} · refinement: {models.get('refine')} "
               f"· documentation: {models.get('document')}_", ""]
    return "\n".join(md)


def _md_cell(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ")


def record_json(rec: MeetingRecord) -> dict:
    data = rec.model_dump()
    data["schema"] = "meetscribe.meeting_record/v1"
    data["notes"] = {"unspecified": f"'{UNSPECIFIED}' means the recording did not state this detail."}
    return data


def tasks_csv(rec: MeetingRecord) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["id", "task", "owner", "owner_stated", "deadline", "deadline_stated", "timestamp", "evidence"])
    for t in rec.action_items:
        w.writerow([t.id, t.task, t.owner, t.owner_stated, t.deadline, t.deadline_stated,
                    _when(t.evidence.start), t.evidence.quote])
    return buf.getvalue()


def corrections_csv(corrections: list[Correction], raw: Transcript) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["segment", "timestamp", "original", "corrected", "category", "reason", "applied", "rejected_because"])
    for c in corrections:
        seg = raw.segment(c.segment_id)
        w.writerow([f"S{c.segment_id}", _when(seg.start if seg else None), c.before, c.after, c.category, c.reason,
                    c.applied, c.rejected_because])
    return buf.getvalue()


HTML_STYLE = """
:root{--bg:#fbfaf7;--ink:#1d1f23;--muted:#62666d;--line:#e3e0d8;--accent:#2f5d50;--chip:#eef3f0;--warn:#8a5a00}
@media (prefers-color-scheme: dark){:root{--bg:#16181b;--ink:#e8e6e1;--muted:#a0a3a8;--line:#2c2f34;--accent:#7fc0a8;--chip:#1f2a26;--warn:#e0b45c}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 Georgia,'Iowan Old Style',serif}
main{max-width:860px;margin:0 auto;padding:40px 20px 80px}h1{font-size:2rem;line-height:1.2;margin:0 0 6px}
h2{font:600 .8rem/1.2 system-ui,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:var(--accent);margin:40px 0 12px;border-top:1px solid var(--line);padding-top:18px}
h3{font-size:1.05rem;margin:18px 0 4px}.meta{color:var(--muted);font:14px/1.5 system-ui,sans-serif}
table{width:100%;border-collapse:collapse;font:14px/1.45 system-ui,sans-serif}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--muted);font-weight:600}.u{color:var(--warn);font-style:italic}.q{color:var(--muted);font-size:.9em;font-style:italic}
.dec{margin:10px 0}.id{font:600 12px system-ui,sans-serif;background:var(--chip);color:var(--accent);padding:2px 6px;border-radius:4px;margin-right:6px}
ul{padding-left:20px}.log{font:13px/1.5 system-ui,sans-serif;color:var(--muted)}
@media print{body{background:#fff;color:#000}h2{color:#000}}
"""


def record_html(rec: MeetingRecord) -> str:
    e = html.escape
    meta = rec.metadata
    parts = [f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' "
             f"content='width=device-width,initial-scale=1'><title>{e(rec.title)}</title><style>{HTML_STYLE}</style>"
             f"</head><body><main><h1>{e(rec.title)}</h1>"]
    facts = []
    if meta.get("source_file"):
        facts.append(f"Recording: {e(meta['source_file'])}")
    if meta.get("duration_s"):
        facts.append(f"Duration: {_ts(meta['duration_s'])}")
    if rec.participants:
        facts.append("People mentioned: " + e(", ".join(rec.participants)))
    parts.append(f"<div class='meta'>{' · '.join(facts)}</div>")
    parts.append(f"<h2>Summary</h2><p>{e(rec.summary)}</p><h2>Minutes</h2>")
    for sec in rec.minutes:
        parts.append(f"<h3>{e(sec.topic)}</h3><ul>" + "".join(f"<li>{e(p)}</li>" for p in sec.points) + "</ul>")
    parts.append("<h2>Key decisions</h2>")
    if rec.decisions:
        for d in rec.decisions:
            parts.append(f"<div class='dec'><span class='id'>{d.id}</span><strong>{e(d.decision)}</strong>"
                         f"<div class='q'>[{_when(d.evidence.start)}] “{e(d.evidence.quote)}”</div></div>")
    else:
        parts.append("<p class='meta'>No decisions were explicitly agreed in this recording.</p>")
    parts.append("<h2>Action items</h2>")
    if rec.action_items:
        parts.append("<table><tr><th>#</th><th>Task</th><th>Owner</th><th>Deadline</th><th>Said at</th></tr>")
        for t in rec.action_items:
            owner = e(t.owner) if t.owner_stated else f"<span class='u'>{UNSPECIFIED}</span>"
            due = e(t.deadline) if t.deadline_stated else f"<span class='u'>{UNSPECIFIED}</span>"
            parts.append(f"<tr><td>{t.id}</td><td>{e(t.task)}</td><td>{owner}</td><td>{due}</td>"
                         f"<td>{_when(t.evidence.start)}</td></tr>")
        parts.append("</table><p class='meta'>“Unspecified” means the recording did not state an owner or deadline.</p>")
    else:
        parts.append("<p class='meta'>No action items were identified.</p>")
    if rec.open_items:
        parts.append("<h2>Open items (not agreed)</h2><ul>" + "".join(
            f"<li><strong>{e(o.kind.capitalize())}:</strong> {e(o.item)}</li>" for o in rec.open_items) + "</ul>")
    parts.append("<h2>Verification</h2><ul class='log'>" + "".join(f"<li>{e(x)}</li>" for x in rec.verification_log)
                 + "</ul>")
    models = meta.get("models", {})
    if models:
        parts.append(f"<p class='log'>Speech-to-text: {e(str(models.get('stt')))} · Refinement: "
                     f"{e(str(models.get('refine')))} · Documentation: {e(str(models.get('document')))}</p>")
    parts.append("</main></body></html>")
    return "".join(parts)


def write_outputs(run_dir: Path, raw: Transcript, refined: Transcript, corrections: list[Correction],
                  record: MeetingRecord) -> dict[str, Path]:
    run_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "raw_transcript": (run_dir / "raw_transcript.txt", transcript_txt(raw, "Raw transcript (speech-to-text)")),
        "refined_transcript": (run_dir / "refined_transcript.txt",
                               transcript_txt(refined, "Refined transcript (domain terms corrected)")),
        "record_md": (run_dir / "meeting_record.md", record_markdown(record)),
        "record_html": (run_dir / "meeting_record.html", record_html(record)),
        "record_json": (run_dir / "meeting_record.json", json.dumps(record_json(record), indent=2, ensure_ascii=False)),
        "tasks_csv": (run_dir / "action_items.csv", tasks_csv(record)),
        "corrections_csv": (run_dir / "corrections.csv", corrections_csv(corrections, raw)),
        "transcripts_json": (run_dir / "transcripts.json", json.dumps(
            {"raw": transcript_json(raw), "refined": transcript_json(refined),
             "dropped_segments": raw.notes}, indent=2, ensure_ascii=False)),
    }
    out = {}
    for key, (path, content) in files.items():
        if path.suffix == ".csv":
            # csv.writer already emits \r\n. Letting Windows translate again produced \r\r\n (blank rows in
            # Excel), so write CSVs untranslated, with a BOM so Excel reads non-ASCII text correctly.
            with open(path, "w", encoding="utf-8-sig", newline="") as fh:
                fh.write(content)
        else:
            path.write_text(content, encoding="utf-8")
        out[key] = path
    bundle = run_dir / "meeting_outputs.zip"
    with zipfile.ZipFile(bundle, "w", zipfile.ZIP_DEFLATED) as z:
        for path in out.values():
            z.write(path, path.name)
    out["bundle"] = bundle
    return out
